### ISSUE TITLE
Can I help maintain this package?

### ISSUE THREAD

**Issue by samvv** [SimonSapin/rust-utf8#8]
Hi there!

Thank you very much for this package. I'd like to make use of it in my own projects, but it looks like the package on crates.io is not in sync with the code in this repository. I can totally understand the difficulty of maintaining lots of packages, which is why I'd like to propose becoming a maintainer of this package.

Let me know what you think!

**Comment by samvv** [comment]
Well, I've just taken a quick look at the source code and the implementation is a bit different than I thought. The offer still stands, though :slightly_smiling_face:

**Comment by SimonSapin** [comment]
Thanks for offering to help! This crate is very small though, so there is not a lot to do.

> it looks like the package on crates.io is not in sync with the code in this repository

Isn’t it? https://crates.io/crates/utf-8/0.7.5 was published on 2019-01-07 which is also the date of the latest commit in https://github.com/SimonSapin/rust-utf8/commits/master

> the implementation is a bit different than I thought

What were you expecting?

**Comment by samvv** [comment]
Hi, oh sorry, that's my mistake! Was a bit too quick. Ion't believe I can be of any value then.

> What were you expecting?

I thought to find a naive implementation of the algorithm, but it seems like you leverage the existing `std` features. Pretty neat I must say!

I'll close this issue.
